name: Go Test CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest  # 使用最新 Ubuntu 环境
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 检出代码[1,3](@ref)

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # 指定 Go 版本[2,6](@ref)

      - name: Run Tests
        run: go test -v -cover ./...  # 运行所有测试并输出覆盖率